// <auto-generated />
using System;
using HrManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HrManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240524001721_InitialCreateCandidate")]
    partial class InitialCreateCandidate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("HrManagement.Domain.Models.Candidate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = "john.doe@example.com",
                            Comments = "Sample comment",
                            CreatedAt = new DateTime(2024, 5, 24, 0, 17, 21, 618, DateTimeKind.Utc).AddTicks(6275),
                            CreatedBy = "admin",
                            FirstName = "John",
                            GitHubUrl = "https://github.com/johndoe",
                            LastModified = new DateTime(2024, 5, 24, 0, 17, 21, 618, DateTimeKind.Utc).AddTicks(6280),
                            LastModifiedBy = "admin",
                            LastName = "Doe",
                            LinkedInUrl = "https://www.linkedin.com/in/johndoe"
                        },
                        new
                        {
                            Id = "jane.doe@example.com",
                            Comments = "Another comment",
                            CreatedAt = new DateTime(2024, 5, 24, 0, 17, 21, 620, DateTimeKind.Utc).AddTicks(1329),
                            CreatedBy = "admin",
                            FirstName = "Jane",
                            GitHubUrl = "https://github.com/janedoe",
                            LastModified = new DateTime(2024, 5, 24, 0, 17, 21, 620, DateTimeKind.Utc).AddTicks(1331),
                            LastModifiedBy = "admin",
                            LastName = "Doe",
                            LinkedInUrl = "https://www.linkedin.com/in/janedoe"
                        });
                });

            modelBuilder.Entity("HrManagement.Domain.Models.Candidate", b =>
                {
                    b.OwnsOne("HrManagement.Domain.ValuesObjects.CallTimeInterval", "CallTimeInterval", b1 =>
                        {
                            b1.Property<string>("CandidateId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("EndTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("EndTime")
                                .HasAnnotation("SqlServer:Sparse", true);

                            b1.Property<DateTime?>("StartTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartTime")
                                .HasAnnotation("SqlServer:Sparse", true);

                            b1.HasKey("CandidateId");

                            b1.ToTable("Candidates");

                            b1.WithOwner()
                                .HasForeignKey("CandidateId");
                        });

                    b.OwnsOne("HrManagement.Domain.ValuesObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<string>("CandidateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .HasColumnType("varchar(20)")
                                .HasColumnName("PhoneNumber")
                                .HasAnnotation("SqlServer:Sparse", true);

                            b1.HasKey("CandidateId");

                            b1.ToTable("Candidates");

                            b1.WithOwner()
                                .HasForeignKey("CandidateId");
                        });

                    b.Navigation("CallTimeInterval");

                    b.Navigation("PhoneNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
